package com.teachpmp.server.entity;

import com.teachpmp.server.entity.base.BasePage;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_bank_info
 *
 * @mbg.generated do_not_delete_during_merge Thu Feb 13 17:39:08 CST 2020
 */
public class BankInfo extends BasePage{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank_info.bank_id
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    private String bankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank_info.bank_no
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    private String bankNo;

    private Integer orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank_info.area_type
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    private String areaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank_info.bank_name
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank_info.train_type
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    private String trainType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank_info.exercise_type
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    private String exerciseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank_info.exercise_num
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    private Integer exerciseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank_info.is_time
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    private String isTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank_info.time
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    private Integer time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank_info.mark_type
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    private String markType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank_info.is_enable
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    private String isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank_info.create_user
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank_info.create_time
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank_info.update_user
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank_info.update_time
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank_info.bank_id
     *
     * @return the value of tb_bank_info.bank_id
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank_info.bank_id
     *
     * @param bankId the value for tb_bank_info.bank_id
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public void setBankId(String bankId) {
        this.bankId = bankId == null ? null : bankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank_info.bank_no
     *
     * @return the value of tb_bank_info.bank_no
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank_info.bank_no
     *
     * @param bankNo the value for tb_bank_info.bank_no
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank_info.area_type
     *
     * @return the value of tb_bank_info.area_type
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public String getAreaType() {
        return areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank_info.area_type
     *
     * @param areaType the value for tb_bank_info.area_type
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public void setAreaType(String areaType) {
        this.areaType = areaType == null ? null : areaType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank_info.bank_name
     *
     * @return the value of tb_bank_info.bank_name
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank_info.bank_name
     *
     * @param bankName the value for tb_bank_info.bank_name
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank_info.train_type
     *
     * @return the value of tb_bank_info.train_type
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public String getTrainType() {
        return trainType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank_info.train_type
     *
     * @param trainType the value for tb_bank_info.train_type
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public void setTrainType(String trainType) {
        this.trainType = trainType == null ? null : trainType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank_info.exercise_type
     *
     * @return the value of tb_bank_info.exercise_type
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public String getExerciseType() {
        return exerciseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank_info.exercise_type
     *
     * @param exerciseType the value for tb_bank_info.exercise_type
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public void setExerciseType(String exerciseType) {
        this.exerciseType = exerciseType == null ? null : exerciseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank_info.exercise_num
     *
     * @return the value of tb_bank_info.exercise_num
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public Integer getExerciseNum() {
        return exerciseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank_info.exercise_num
     *
     * @param exerciseNum the value for tb_bank_info.exercise_num
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public void setExerciseNum(Integer exerciseNum) {
        this.exerciseNum = exerciseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank_info.is_time
     *
     * @return the value of tb_bank_info.is_time
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public String getIsTime() {
        return isTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank_info.is_time
     *
     * @param isTime the value for tb_bank_info.is_time
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public void setIsTime(String isTime) {
        this.isTime = isTime == null ? null : isTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank_info.time
     *
     * @return the value of tb_bank_info.time
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank_info.time
     *
     * @param time the value for tb_bank_info.time
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank_info.mark_type
     *
     * @return the value of tb_bank_info.mark_type
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public String getMarkType() {
        return markType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank_info.mark_type
     *
     * @param markType the value for tb_bank_info.mark_type
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public void setMarkType(String markType) {
        this.markType = markType == null ? null : markType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank_info.is_enable
     *
     * @return the value of tb_bank_info.is_enable
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank_info.is_enable
     *
     * @param isEnable the value for tb_bank_info.is_enable
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable == null ? null : isEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank_info.create_user
     *
     * @return the value of tb_bank_info.create_user
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank_info.create_user
     *
     * @param createUser the value for tb_bank_info.create_user
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank_info.create_time
     *
     * @return the value of tb_bank_info.create_time
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank_info.create_time
     *
     * @param createTime the value for tb_bank_info.create_time
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank_info.update_user
     *
     * @return the value of tb_bank_info.update_user
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank_info.update_user
     *
     * @param updateUser the value for tb_bank_info.update_user
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank_info.update_time
     *
     * @return the value of tb_bank_info.update_time
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank_info.update_time
     *
     * @param updateTime the value for tb_bank_info.update_time
     *
     * @mbg.generated Thu Feb 13 17:39:08 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    private int doNum = 0;
    private String doStatus;

    public int getDoNum() {
        return doNum;
    }

    public void setDoNum(int doNum) {
        this.doNum = doNum;
    }

    public String getDoStatus() {
        if(doNum == 0){
            doStatus = "未开始";
        }else if(doNum > 0 & doNum< exerciseNum){
            doStatus = "做题中";
        }else{
            doStatus = "重新开始";
        }
        return doStatus;
    }

    public void setDoStatus(String doStatus) {
        this.doStatus = doStatus;
    }
}