package com.teachpmp.server.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.teachpmp.server.entity.base.BasePage;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_class_info
 *
 * @mbg.generated do_not_delete_during_merge Thu Feb 13 13:00:58 CST 2020
 */
public class ClassInfo extends BasePage{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class_info.class_id
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    private String classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class_info.class_name
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class_info.area_type
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    private String areaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class_info.create_time
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd  HH:mm:ss")
    private Date createTime;
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class_info.update_user
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class_info.update_time
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class_info.class_id
     *
     * @return the value of tb_class_info.class_id
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class_info.class_id
     *
     * @param classId the value for tb_class_info.class_id
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class_info.class_name
     *
     * @return the value of tb_class_info.class_name
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class_info.class_name
     *
     * @param className the value for tb_class_info.class_name
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class_info.area_type
     *
     * @return the value of tb_class_info.area_type
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    public String getAreaType() {
        return areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class_info.area_type
     *
     * @param areaType the value for tb_class_info.area_type
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    public void setAreaType(String areaType) {
        this.areaType = areaType == null ? null : areaType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class_info.create_time
     *
     * @return the value of tb_class_info.create_time
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class_info.create_time
     *
     * @param createTime the value for tb_class_info.create_time
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class_info.update_user
     *
     * @return the value of tb_class_info.update_user
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class_info.update_user
     *
     * @param updateUser the value for tb_class_info.update_user
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class_info.update_time
     *
     * @return the value of tb_class_info.update_time
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class_info.update_time
     *
     * @param updateTime the value for tb_class_info.update_time
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }
}