package com.teachpmp.server.entity;

import com.teachpmp.server.entity.base.BasePage;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_dictionary_info
 *
 * @mbg.generated do_not_delete_during_merge Sun Feb 09 14:11:43 CST 2020
 */
public class Dictionary extends BasePage{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary_info.dictionary_id
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    private String dictionaryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary_info.type_name
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary_info.type_code
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary_info.dictionary_name
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    private String dictionaryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary_info.dictionary_code
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    private String dictionaryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary_info.remarks
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    private String remarks;
    private Integer orderNo;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary_info.create_user
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary_info.create_time
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary_info.update_user
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary_info.update_time
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary_info.dictionary_id
     *
     * @return the value of tb_dictionary_info.dictionary_id
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public String getDictionaryId() {
        return dictionaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary_info.dictionary_id
     *
     * @param dictionaryId the value for tb_dictionary_info.dictionary_id
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public void setDictionaryId(String dictionaryId) {
        this.dictionaryId = dictionaryId == null ? null : dictionaryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary_info.type_name
     *
     * @return the value of tb_dictionary_info.type_name
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary_info.type_name
     *
     * @param typeName the value for tb_dictionary_info.type_name
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary_info.type_code
     *
     * @return the value of tb_dictionary_info.type_code
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary_info.type_code
     *
     * @param typeCode the value for tb_dictionary_info.type_code
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary_info.dictionary_name
     *
     * @return the value of tb_dictionary_info.dictionary_name
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public String getDictionaryName() {
        return dictionaryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary_info.dictionary_name
     *
     * @param dictionaryName the value for tb_dictionary_info.dictionary_name
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public void setDictionaryName(String dictionaryName) {
        this.dictionaryName = dictionaryName == null ? null : dictionaryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary_info.dictionary_code
     *
     * @return the value of tb_dictionary_info.dictionary_code
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public String getDictionaryCode() {
        return dictionaryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary_info.dictionary_code
     *
     * @param dictionaryCode the value for tb_dictionary_info.dictionary_code
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public void setDictionaryCode(String dictionaryCode) {
        this.dictionaryCode = dictionaryCode == null ? null : dictionaryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary_info.remarks
     *
     * @return the value of tb_dictionary_info.remarks
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary_info.remarks
     *
     * @param remarks the value for tb_dictionary_info.remarks
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary_info.create_user
     *
     * @return the value of tb_dictionary_info.create_user
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary_info.create_user
     *
     * @param createUser the value for tb_dictionary_info.create_user
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary_info.create_time
     *
     * @return the value of tb_dictionary_info.create_time
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary_info.create_time
     *
     * @param createTime the value for tb_dictionary_info.create_time
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary_info.update_user
     *
     * @return the value of tb_dictionary_info.update_user
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary_info.update_user
     *
     * @param updateUser the value for tb_dictionary_info.update_user
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary_info.update_time
     *
     * @return the value of tb_dictionary_info.update_time
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary_info.update_time
     *
     * @param updateTime the value for tb_dictionary_info.update_time
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }
}