package com.teachpmp.server.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_error_info
 *
 * @mbg.generated do_not_delete_during_merge Fri Feb 28 16:04:58 CST 2020
 */
public class ErrorBook {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_error_info.error_id
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    private String errorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_error_info.student_id
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_error_info.student_name
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_error_info.train_type
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    private String trainType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_error_info.exercise_type
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    private String exerciseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_error_info.bank_id
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    private String bankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_error_info.bank_name
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_error_info.excer_id
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    private String excerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_error_info.order_no
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    private Integer orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_error_info.selection_answer
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    private String selectionAnswer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_error_info.is_remove
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    private String isRemove;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_error_info.error_id
     *
     * @return the value of tb_error_info.error_id
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public String getErrorId() {
        return errorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_error_info.error_id
     *
     * @param errorId the value for tb_error_info.error_id
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public void setErrorId(String errorId) {
        this.errorId = errorId == null ? null : errorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_error_info.student_id
     *
     * @return the value of tb_error_info.student_id
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_error_info.student_id
     *
     * @param studentId the value for tb_error_info.student_id
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_error_info.student_name
     *
     * @return the value of tb_error_info.student_name
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_error_info.student_name
     *
     * @param studentName the value for tb_error_info.student_name
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_error_info.train_type
     *
     * @return the value of tb_error_info.train_type
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public String getTrainType() {
        return trainType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_error_info.train_type
     *
     * @param trainType the value for tb_error_info.train_type
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public void setTrainType(String trainType) {
        this.trainType = trainType == null ? null : trainType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_error_info.exercise_type
     *
     * @return the value of tb_error_info.exercise_type
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public String getExerciseType() {
        return exerciseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_error_info.exercise_type
     *
     * @param exerciseType the value for tb_error_info.exercise_type
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public void setExerciseType(String exerciseType) {
        this.exerciseType = exerciseType == null ? null : exerciseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_error_info.bank_id
     *
     * @return the value of tb_error_info.bank_id
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_error_info.bank_id
     *
     * @param bankId the value for tb_error_info.bank_id
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public void setBankId(String bankId) {
        this.bankId = bankId == null ? null : bankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_error_info.bank_name
     *
     * @return the value of tb_error_info.bank_name
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_error_info.bank_name
     *
     * @param bankName the value for tb_error_info.bank_name
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_error_info.excer_id
     *
     * @return the value of tb_error_info.excer_id
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public String getExcerId() {
        return excerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_error_info.excer_id
     *
     * @param excerId the value for tb_error_info.excer_id
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public void setExcerId(String excerId) {
        this.excerId = excerId == null ? null : excerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_error_info.order_no
     *
     * @return the value of tb_error_info.order_no
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_error_info.order_no
     *
     * @param orderNo the value for tb_error_info.order_no
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_error_info.selection_answer
     *
     * @return the value of tb_error_info.selection_answer
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public String getSelectionAnswer() {
        return selectionAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_error_info.selection_answer
     *
     * @param selectionAnswer the value for tb_error_info.selection_answer
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public void setSelectionAnswer(String selectionAnswer) {
        this.selectionAnswer = selectionAnswer == null ? null : selectionAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_error_info.is_remove
     *
     * @return the value of tb_error_info.is_remove
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public String getIsRemove() {
        return isRemove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_error_info.is_remove
     *
     * @param isRemove the value for tb_error_info.is_remove
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    public void setIsRemove(String isRemove) {
        this.isRemove = isRemove == null ? null : isRemove.trim();
    }
}