package com.teachpmp.server.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.teachpmp.server.entity.base.BasePage;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_role_info
 *
 * @mbg.generated do_not_delete_during_merge Sun Feb 09 14:21:47 CST 2020
 */
public class Role extends BasePage{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_info.role_id
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    private String roleId;

    private String userId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_info.role_name
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    private String roleName;
    private String roleCode;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_info.role_remarks
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    private String roleRemarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_info.create_user
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_info.create_time
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd  HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_info.update_user
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_info.update_time
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_info.role_id
     *
     * @return the value of tb_role_info.role_id
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_info.role_id
     *
     * @param roleId the value for tb_role_info.role_id
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_info.role_name
     *
     * @return the value of tb_role_info.role_name
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_info.role_name
     *
     * @param roleName the value for tb_role_info.role_name
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_info.role_remarks
     *
     * @return the value of tb_role_info.role_remarks
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    public String getRoleRemarks() {
        return roleRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_info.role_remarks
     *
     * @param roleRemarks the value for tb_role_info.role_remarks
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    public void setRoleRemarks(String roleRemarks) {
        this.roleRemarks = roleRemarks == null ? null : roleRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_info.create_user
     *
     * @return the value of tb_role_info.create_user
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_info.create_user
     *
     * @param createUser the value for tb_role_info.create_user
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_info.create_time
     *
     * @return the value of tb_role_info.create_time
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_info.create_time
     *
     * @param createTime the value for tb_role_info.create_time
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_info.update_user
     *
     * @return the value of tb_role_info.update_user
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_info.update_user
     *
     * @param updateUser the value for tb_role_info.update_user
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_info.update_time
     *
     * @return the value of tb_role_info.update_time
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_info.update_time
     *
     * @param updateTime the value for tb_role_info.update_time
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getRoleCode() {
        return roleCode;
    }

    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
}