package com.teachpmp.server.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_score_info
 *
 * @mbg.generated do_not_delete_during_merge Thu Feb 27 20:36:06 CST 2020
 */
public class Score {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_info.score_id
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    private String scoreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_info.class_id
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    private String classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_info.class_name
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_info.student_id
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_info.student_name
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_info.train_type
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    private String trainType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_info.exercise_type
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    private String exerciseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_info.bank_id
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    private String bankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_info.bank_name
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_info.right_exercise_num
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    private Integer rightExerciseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_info.exercise_num
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    private Integer exerciseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_info.score
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_info.score_time
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    private Date scoreTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_info.score_id
     *
     * @return the value of tb_score_info.score_id
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public String getScoreId() {
        return scoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_info.score_id
     *
     * @param scoreId the value for tb_score_info.score_id
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public void setScoreId(String scoreId) {
        this.scoreId = scoreId == null ? null : scoreId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_info.class_id
     *
     * @return the value of tb_score_info.class_id
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_info.class_id
     *
     * @param classId the value for tb_score_info.class_id
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_info.class_name
     *
     * @return the value of tb_score_info.class_name
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_info.class_name
     *
     * @param className the value for tb_score_info.class_name
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_info.student_id
     *
     * @return the value of tb_score_info.student_id
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_info.student_id
     *
     * @param studentId the value for tb_score_info.student_id
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_info.student_name
     *
     * @return the value of tb_score_info.student_name
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_info.student_name
     *
     * @param studentName the value for tb_score_info.student_name
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_info.train_type
     *
     * @return the value of tb_score_info.train_type
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public String getTrainType() {
        return trainType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_info.train_type
     *
     * @param trainType the value for tb_score_info.train_type
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public void setTrainType(String trainType) {
        this.trainType = trainType == null ? null : trainType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_info.exercise_type
     *
     * @return the value of tb_score_info.exercise_type
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public String getExerciseType() {
        return exerciseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_info.exercise_type
     *
     * @param exerciseType the value for tb_score_info.exercise_type
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public void setExerciseType(String exerciseType) {
        this.exerciseType = exerciseType == null ? null : exerciseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_info.bank_id
     *
     * @return the value of tb_score_info.bank_id
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_info.bank_id
     *
     * @param bankId the value for tb_score_info.bank_id
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public void setBankId(String bankId) {
        this.bankId = bankId == null ? null : bankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_info.bank_name
     *
     * @return the value of tb_score_info.bank_name
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_info.bank_name
     *
     * @param bankName the value for tb_score_info.bank_name
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_info.right_exercise_num
     *
     * @return the value of tb_score_info.right_exercise_num
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public Integer getRightExerciseNum() {
        return rightExerciseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_info.right_exercise_num
     *
     * @param rightExerciseNum the value for tb_score_info.right_exercise_num
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public void setRightExerciseNum(Integer rightExerciseNum) {
        this.rightExerciseNum = rightExerciseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_info.exercise_num
     *
     * @return the value of tb_score_info.exercise_num
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public Integer getExerciseNum() {
        return exerciseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_info.exercise_num
     *
     * @param exerciseNum the value for tb_score_info.exercise_num
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public void setExerciseNum(Integer exerciseNum) {
        this.exerciseNum = exerciseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_info.score
     *
     * @return the value of tb_score_info.score
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_info.score
     *
     * @param score the value for tb_score_info.score
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_info.score_time
     *
     * @return the value of tb_score_info.score_time
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public Date getScoreTime() {
        return scoreTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_info.score_time
     *
     * @param scoreTime the value for tb_score_info.score_time
     *
     * @mbg.generated Thu Feb 27 20:36:06 CST 2020
     */
    public void setScoreTime(Date scoreTime) {
        this.scoreTime = scoreTime;
    }
}