package com.teachpmp.server.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_student_answer_info
 *
 * @mbg.generated do_not_delete_during_merge Tue Feb 25 17:44:43 CST 2020
 */
public class StudentAnswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_answer_info.student_answer_id
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    private String studentAnswerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_answer_info.area_type
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    private String areaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_answer_info.student_id
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_answer_info.student_name
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_answer_info.train_type
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    private String trainType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_answer_info.exercise_type
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    private String exerciseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_answer_info.bank_id
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    private String bankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_answer_info.bank_name
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_answer_info.excer_id
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    private String excerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_answer_info.order_no
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    private Integer orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_answer_info.selection_correct
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    private String selectionCorrect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_answer_info.selection_answer
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    private String selectionAnswer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_answer_info.is_right
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    private String isRight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_answer_info.create_time
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_answer_info.update_time
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    private Date updateTime;

    private String isErrorBook;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_answer_info.student_answer_id
     *
     * @return the value of tb_student_answer_info.student_answer_id
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public String getStudentAnswerId() {
        return studentAnswerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_answer_info.student_answer_id
     *
     * @param studentAnswerId the value for tb_student_answer_info.student_answer_id
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public void setStudentAnswerId(String studentAnswerId) {
        this.studentAnswerId = studentAnswerId == null ? null : studentAnswerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_answer_info.area_type
     *
     * @return the value of tb_student_answer_info.area_type
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public String getAreaType() {
        return areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_answer_info.area_type
     *
     * @param areaType the value for tb_student_answer_info.area_type
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public void setAreaType(String areaType) {
        this.areaType = areaType == null ? null : areaType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_answer_info.student_id
     *
     * @return the value of tb_student_answer_info.student_id
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_answer_info.student_id
     *
     * @param studentId the value for tb_student_answer_info.student_id
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_answer_info.student_name
     *
     * @return the value of tb_student_answer_info.student_name
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_answer_info.student_name
     *
     * @param studentName the value for tb_student_answer_info.student_name
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_answer_info.train_type
     *
     * @return the value of tb_student_answer_info.train_type
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public String getTrainType() {
        return trainType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_answer_info.train_type
     *
     * @param trainType the value for tb_student_answer_info.train_type
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public void setTrainType(String trainType) {
        this.trainType = trainType == null ? null : trainType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_answer_info.exercise_type
     *
     * @return the value of tb_student_answer_info.exercise_type
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public String getExerciseType() {
        return exerciseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_answer_info.exercise_type
     *
     * @param exerciseType the value for tb_student_answer_info.exercise_type
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public void setExerciseType(String exerciseType) {
        this.exerciseType = exerciseType == null ? null : exerciseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_answer_info.bank_id
     *
     * @return the value of tb_student_answer_info.bank_id
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_answer_info.bank_id
     *
     * @param bankId the value for tb_student_answer_info.bank_id
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public void setBankId(String bankId) {
        this.bankId = bankId == null ? null : bankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_answer_info.bank_name
     *
     * @return the value of tb_student_answer_info.bank_name
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_answer_info.bank_name
     *
     * @param bankName the value for tb_student_answer_info.bank_name
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_answer_info.excer_id
     *
     * @return the value of tb_student_answer_info.excer_id
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public String getExcerId() {
        return excerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_answer_info.excer_id
     *
     * @param excerId the value for tb_student_answer_info.excer_id
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public void setExcerId(String excerId) {
        this.excerId = excerId == null ? null : excerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_answer_info.order_no
     *
     * @return the value of tb_student_answer_info.order_no
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_answer_info.order_no
     *
     * @param orderNo the value for tb_student_answer_info.order_no
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_answer_info.selection_correct
     *
     * @return the value of tb_student_answer_info.selection_correct
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public String getSelectionCorrect() {
        return selectionCorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_answer_info.selection_correct
     *
     * @param selectionCorrect the value for tb_student_answer_info.selection_correct
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public void setSelectionCorrect(String selectionCorrect) {
        this.selectionCorrect = selectionCorrect == null ? null : selectionCorrect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_answer_info.selection_answer
     *
     * @return the value of tb_student_answer_info.selection_answer
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public String getSelectionAnswer() {
        return selectionAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_answer_info.selection_answer
     *
     * @param selectionAnswer the value for tb_student_answer_info.selection_answer
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public void setSelectionAnswer(String selectionAnswer) {
        this.selectionAnswer = selectionAnswer == null ? null : selectionAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_answer_info.is_right
     *
     * @return the value of tb_student_answer_info.is_right
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public String getIsRight() {
        return isRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_answer_info.is_right
     *
     * @param isRight the value for tb_student_answer_info.is_right
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public void setIsRight(String isRight) {
        this.isRight = isRight == null ? null : isRight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_answer_info.create_time
     *
     * @return the value of tb_student_answer_info.create_time
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_answer_info.create_time
     *
     * @param createTime the value for tb_student_answer_info.create_time
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_answer_info.update_time
     *
     * @return the value of tb_student_answer_info.update_time
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_answer_info.update_time
     *
     * @param updateTime the value for tb_student_answer_info.update_time
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getIsErrorBook() {
        return isErrorBook;
    }

    public void setIsErrorBook(String isErrorBook) {
        this.isErrorBook = isErrorBook;
    }
}