package com.teachpmp.server.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.teachpmp.server.entity.base.BasePage;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_student_info
 *
 * @mbg.generated do_not_delete_during_merge Sun Feb 16 13:53:15 CST 2020
 */
public class Student extends BasePage{


    private String openid;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_info.student_id
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    private String studentId;

    private String className;
    private String areaTypeName;
    private String statusName;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_info.class_id
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    private String classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_info.area_type
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    private String areaType;
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_info.student_name
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_info.sex
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_info.phone_no
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_info.email
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_info.wechat
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_info.expiry_date
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date expiryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_info.is_authorize
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    private String isAuthorize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_info.create_time
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_info.update_user
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_info.update_time
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student_info.create_user
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    private String createUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_info.student_id
     *
     * @return the value of tb_student_info.student_id
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_info.student_id
     *
     * @param studentId the value for tb_student_info.student_id
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_info.class_id
     *
     * @return the value of tb_student_info.class_id
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_info.class_id
     *
     * @param classId the value for tb_student_info.class_id
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_info.area_type
     *
     * @return the value of tb_student_info.area_type
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public String getAreaType() {
        return areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_info.area_type
     *
     * @param areaType the value for tb_student_info.area_type
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public void setAreaType(String areaType) {
        this.areaType = areaType == null ? null : areaType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_info.student_name
     *
     * @return the value of tb_student_info.student_name
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_info.student_name
     *
     * @param studentName the value for tb_student_info.student_name
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_info.sex
     *
     * @return the value of tb_student_info.sex
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_info.sex
     *
     * @param sex the value for tb_student_info.sex
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_info.phone_no
     *
     * @return the value of tb_student_info.phone_no
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_info.phone_no
     *
     * @param phoneNo the value for tb_student_info.phone_no
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_info.email
     *
     * @return the value of tb_student_info.email
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_info.email
     *
     * @param email the value for tb_student_info.email
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_info.wechat
     *
     * @return the value of tb_student_info.wechat
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_info.wechat
     *
     * @param wechat the value for tb_student_info.wechat
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_info.expiry_date
     *
     * @return the value of tb_student_info.expiry_date
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public Date getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_info.expiry_date
     *
     * @param expiryDate the value for tb_student_info.expiry_date
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_info.is_authorize
     *
     * @return the value of tb_student_info.is_authorize
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public String getIsAuthorize() {
        return isAuthorize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_info.is_authorize
     *
     * @param isAuthorize the value for tb_student_info.is_authorize
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public void setIsAuthorize(String isAuthorize) {
        this.isAuthorize = isAuthorize == null ? null : isAuthorize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_info.create_time
     *
     * @return the value of tb_student_info.create_time
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_info.create_time
     *
     * @param createTime the value for tb_student_info.create_time
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_info.update_user
     *
     * @return the value of tb_student_info.update_user
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_info.update_user
     *
     * @param updateUser the value for tb_student_info.update_user
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_info.update_time
     *
     * @return the value of tb_student_info.update_time
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_info.update_time
     *
     * @param updateTime the value for tb_student_info.update_time
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student_info.create_user
     *
     * @return the value of tb_student_info.create_user
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student_info.create_user
     *
     * @param createUser the value for tb_student_info.create_user
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getOpenid() {
        return openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }

    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public String getAreaTypeName() {
        return areaTypeName;
    }

    public void setAreaTypeName(String areaTypeName) {
        this.areaTypeName = areaTypeName;
    }

    public String getStatusName() {
        return statusName;
    }

    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }
}