package com.teachpmp.server.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.teachpmp.server.entity.base.BasePage;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_user_info
 *
 * @mbg.generated do_not_delete_during_merge Sun Feb 09 14:15:49 CST 2020
 */
public class User extends BasePage{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.user_id
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    private String userId;
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.user_name
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.sex
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.phone_no
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.account
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.password
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.email
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.is_enable
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    private String isEnable;

    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date expiryDate;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.create_user
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.create_time
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd  HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.update_user
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.update_time
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.user_id
     *
     * @return the value of tb_user_info.user_id
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.user_id
     *
     * @param userId the value for tb_user_info.user_id
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.user_name
     *
     * @return the value of tb_user_info.user_name
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.user_name
     *
     * @param userName the value for tb_user_info.user_name
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.sex
     *
     * @return the value of tb_user_info.sex
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.sex
     *
     * @param sex the value for tb_user_info.sex
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.phone_no
     *
     * @return the value of tb_user_info.phone_no
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.phone_no
     *
     * @param phoneNo the value for tb_user_info.phone_no
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.account
     *
     * @return the value of tb_user_info.account
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.account
     *
     * @param account the value for tb_user_info.account
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.password
     *
     * @return the value of tb_user_info.password
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.password
     *
     * @param password the value for tb_user_info.password
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.email
     *
     * @return the value of tb_user_info.email
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.email
     *
     * @param email the value for tb_user_info.email
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.is_enable
     *
     * @return the value of tb_user_info.is_enable
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.is_enable
     *
     * @param isEnable the value for tb_user_info.is_enable
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable == null ? null : isEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.create_user
     *
     * @return the value of tb_user_info.create_user
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.create_user
     *
     * @param createUser the value for tb_user_info.create_user
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.create_time
     *
     * @return the value of tb_user_info.create_time
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.create_time
     *
     * @param createTime the value for tb_user_info.create_time
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.update_user
     *
     * @return the value of tb_user_info.update_user
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.update_user
     *
     * @param updateUser the value for tb_user_info.update_user
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.update_time
     *
     * @return the value of tb_user_info.update_time
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.update_time
     *
     * @param updateTime the value for tb_user_info.update_time
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Date getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    public String getRoleId() {
        return roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
}