package com.teachpmp.server.dao;

import com.teachpmp.server.entity.ClassInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ClassInfoMapper extends BaseMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class_info
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    int deleteByPrimaryKey(String classId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class_info
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    int insert(ClassInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class_info
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    ClassInfo selectByPrimaryKey(String classId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class_info
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    List<ClassInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class_info
     *
     * @mbg.generated Thu Feb 13 13:00:58 CST 2020
     */
    int updateByPrimaryKey(ClassInfo record);
    ClassInfo getClassByName(String areaType, String className);

}