package com.teachpmp.server.dao;

import com.teachpmp.server.entity.Dictionary;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface DictionaryMapper extends BaseMapper<Dictionary>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dictionary_info
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    int deleteByPrimaryKey(String dictionaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dictionary_info
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    int insert(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dictionary_info
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    Dictionary selectByPrimaryKey(String dictionaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dictionary_info
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    List<Dictionary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dictionary_info
     *
     * @mbg.generated Sun Feb 09 14:11:43 CST 2020
     */
    int updateByPrimaryKey(Dictionary record);


    Dictionary getDicByDicCode(@Param("typeCode") String typeCode, @Param("dicCode") String dicCode) ;
    Dictionary getDicByTypeCode(String typeCode);
    int updateTypeByPrimaryKey(Dictionary record);
    int updateType(String oldTypeCode, String typeCode, String typeName);
    int deleteType(String typeCode);
    List<Dictionary> pageDic(String typeCode);
}