package com.teachpmp.server.dao;

import com.teachpmp.server.entity.ErrorBook;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ErrorBookMapper extends BaseMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_error_info
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    int deleteByPrimaryKey(String errorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_error_info
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    int insert(ErrorBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_error_info
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    ErrorBook selectByPrimaryKey(String errorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_error_info
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    List<ErrorBook> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_error_info
     *
     * @mbg.generated Fri Feb 28 16:04:58 CST 2020
     */
    int updateByPrimaryKey(ErrorBook record);

    void removeError(String studentId, String excerId);
    void removeRight(@Param("studentId") String studentId, @Param("excerIds") String[] excerIds);
    Integer getErrorCount(String studentId, String trainType);
    ErrorBook getErrorExercise(String studentId, String trainType);
}