package com.teachpmp.server.dao;

import com.teachpmp.server.entity.Exercise;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ExerciseMapper extends BaseMapper<Exercise>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_exercise_info
     *
     * @mbg.generated Fri Feb 14 18:30:57 CST 2020
     */
    int deleteByPrimaryKey(String excerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_exercise_info
     *
     * @mbg.generated Fri Feb 14 18:30:57 CST 2020
     */
    int insert(Exercise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_exercise_info
     *
     * @mbg.generated Fri Feb 14 18:30:57 CST 2020
     */
    Exercise selectByPrimaryKey(String excerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_exercise_info
     *
     * @mbg.generated Fri Feb 14 18:30:57 CST 2020
     */
    List<Exercise> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_exercise_info
     *
     * @mbg.generated Fri Feb 14 18:30:57 CST 2020
     */
    int updateByPrimaryKey(Exercise record);

    Exercise getExercise(Exercise exercise);
    void multiDelete(@Param("excerIds") String[] excerIds);
    int deleteByBankId(String bankId);
    Integer countExercise(@Param("bankId") String bankId);
}