package com.teachpmp.server.dao;

import com.teachpmp.server.entity.Role;
import com.teachpmp.server.entity.RoleResource;
import com.teachpmp.server.entity.RoleUser;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface RoleMapper extends BaseMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_info
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_info
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_info
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    Role selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_info
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    List<Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_info
     *
     * @mbg.generated Sun Feb 09 14:21:47 CST 2020
     */
    int updateByPrimaryKey(Role record);


    Role getRoleByName(String roleCode);

    int deleteByUserId(String userId);
    int deleteByRoleId(String roleId);
    int deleteMenuByRoleId(String roleId);
    List<String> getResourceIds(String roleId);
    List<String> getResourceByUser(String userId);

    int addBatch(@Param("roleUsers") List<RoleUser> roleUsers);
    public int addBatchResource(@Param("roleResources") List<RoleResource> roleResources);
}