package com.teachpmp.server.dao;

import com.teachpmp.server.entity.Student;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StudentMapper extends BaseMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student_info
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    int deleteByPrimaryKey(String studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student_info
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student_info
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    Student selectByPrimaryKey(String studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student_info
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    List<Student> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student_info
     *
     * @mbg.generated Sun Feb 16 13:53:15 CST 2020
     */
    int updateByPrimaryKey(Student record);
    Student selectOne(Student student);
    int countStudent();
    int deleteClass(String classId);
}