package com.teachpmp.server.dao;

import com.teachpmp.server.entity.StudentAnswer;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface StudentAnswerMapper extends BaseMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student_answer_info
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    int deleteByPrimaryKey(String studentAnswerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student_answer_info
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    int insert(StudentAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student_answer_info
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    StudentAnswer selectByPrimaryKey(String studentAnswerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student_answer_info
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    List<StudentAnswer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student_answer_info
     *
     * @mbg.generated Tue Feb 25 17:44:43 CST 2020
     */
    int updateByPrimaryKey(StudentAnswer record);

    String getAnswer(String studentId, String bankId, String excerId, String isErrorBook);

    Integer getDoNum(String studentId, String bankId);
    Integer getRight(String studentId, String bankId);
    List<StudentAnswer> getAswers(String studentId, String bankId);
    List<String> getRightExercise(String studentId);
    void restExercise(@Param("studentId") String studentId, @Param("bankId")String bankId, @Param("isErrorBook")String isErrorBook);
}