package com.teachpmp.server.dao;

import com.teachpmp.server.entity.User;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface UserMapper extends BaseMapper<User>{

    User getUserByAccount(String account);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    User selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbg.generated Sun Feb 09 14:15:49 CST 2020
     */
    int updateByPrimaryKey(User record);


    List<User> page(User user);
}